---
settings:
  name: BlueXP cloud ops
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti relativi alle operazioni cloud BlueXP
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Scopri le operazioni cloud di BlueXP
      url: "/concept-compute.html"
    - title: Collegare l'account AWS
      url: "/task-getting-started-compute.html"
  - title: Analizza i costi di calcolo
    url: "/task-analyze-costs.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Scopri le operazioni cloud di BlueXP
      url: concept-compute.html
    - title: Collegare l'account AWS
      url: task-getting-started-compute.html
  - title: Utilizza le operazioni cloud di BlueXP
    links:
    - title: Analizza i costi di calcolo
      url: task-analyze-costs.html
  - title: Blog e community
    links:
    - title: Community NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://cloud.netapp.com/blog
    - title: Webinar sul cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
